# AUTOGENERATED! DO NOT EDIT! File to edit: ../publication.ipynb.

# %% auto 0
__all__ = ['Publication']

# %% ../publication.ipynb 3
class Publication:
    def __init__(self, id, title, doi):
        self.id = id
        self.title = title
        self.doi = doi

    def __repr__(self):
        return self.title
